### ISSUE TITLE
Attempting to submit issue to defect tracker without proper access yields non-formatted error message

### ISSUE THREAD

**Issue by RTimmonsDG** [denimgroup/threadfix#1040]
A user with JIRA's "Browse Projects" permission can attach JIRA as a defect tracker to an application in ThreadFix.  When this user attempts to submit a defect to JIRA without having JIRA's "Create Issue" permission, the following dialogue appears warning that ThreadFix can't fetch the dynamic fields:
![image](https://cloud.githubusercontent.com/assets/10927116/6699086/a682c7f8-cccc-11e4-9dda-b92295066e33.png)
If the user continues to click the "Submit Defect" button, an unformatted error message appears.
![image](https://cloud.githubusercontent.com/assets/10927116/6699115/dc014896-cccc-11e4-90ec-5ddc44be4e3b.png)

**Comment by dg-mcollins** [comment]
This will be fixed in the 2.2 official release.
