### ISSUE TITLE
CSFR filter addresses not all loaded

### ISSUE THREAD

**Issue by geoffreydudragne** [denimgroup/threadfix#1092]
In the web.xml, the last 30 lines of the CSFR filter addresses are not loaded because they don't have the comma at the end of the address. I don't know if this is actually an issue or if it is on purpose.

But at usage with often end up with csrf errors and asked to refresh the page.

**Comment by dg-mcollins** [comment]
Thanks for the tip. We've fixed it in https://github.com/denimgroup/threadfix/commit/a2cc53d6817ce61be292df562b7a8b59483945da

**Comment by dg-mcollins** [comment]
This will go out in 2.2.1
