### ISSUE TITLE
Action button is not longer visable

### ISSUE THREAD

**Issue by sbehrens** [denimgroup/threadfix#1093]
Hello,

The action button is no longer visible
![screen shot 2015-04-16 at 12 13 44 pm](https://cloud.githubusercontent.com/assets/688589/7189222/44a1895c-e432-11e4-84fa-5ad5f3f094a0.png)

I was using the actions for marking issues as false positive.  Not sure why, but the button or checkbox dropdowns no longer exist.  Can you help?

**Comment by johnbeoris** [comment]
I believe that you are on the Team Detail Page in this screenshot. The action button in that location is only available when on the Application Index Page.

**Comment by sbehrens** [comment]
Hi John,

That seems to be correct.  Is there a way to bulk select issues based on team?  From a recently scan of about 1000 applications 95% are false positive and clicking each application to mark false positives is non scalable.

**Comment by johnbeoris** [comment]
Hey Scott,

I have made a note of this and filed it as a feature request. Thank you!

**Comment by sbehrens** [comment]
Thanks John!
