### ISSUE TITLE
An unexpected request on application detail page

### ISSUE THREAD

**Issue by geoffreydudragne** [denimgroup/threadfix#1133]
When opening "/threadfix/organizations/[0-9]+/applications/[0-9]+"

The request "POST /threadfix/reports/tree" is fired 2 times:

The first time with only the parameter:
usingComponentsWithKnownVulnerabilities=false

The second time with all the normal the parameters:
applications[0].id=[0-9]+
numberVulnerabilities=[0-9]+
showClosed=false
showDefectClosed=false
showDefectNotPresent=false
showDefectOpen=false
showDefectPresent=false
showFalsePositive=false
showHidden=false
showOpen=true
usingComponentsWithKnownVulnerabilities=false

The first request seems undesired and has for result to display all the vulnerabilities in Threadfix  (because no application filter) for an instant before the second request refreshes and displays the ones we want. Doesn't trouble the normal use, but the result is visually weird and jumpy.

**Comment by dg-mcollins** [comment]
Hi Geoffrey,

This is a duplicate of https://github.com/denimgroup/threadfix/issues/1084. We have fixed it in the 2.2.2 version of ThreadFix. What version are you using?

Thanks,
Mac

**Comment by geoffreydudragne** [comment]
Oh sorry, indeed I'm still currently on 2.2.1
