### ISSUE TITLE
ThreadFix license check failed. Install a valid license and try again.

### ISSUE THREAD

**Issue by antrich9** [denimgroup/threadfix#1144]
Starting Threadfix is throwing the following error when using the community edition:

ThreadFix license check failed. Install a valid license and try again.

**Comment by dancornell** [comment]
Sorry for the delay on getting back to you on GitHub about this. The day you submitted this you should have received an email from the ThreadFix support team, but I wanted to also reach out here just to make sure we'd cleared the issue for you.

If you re-download ThreadFix that should fix the issue. Also in the meantime we've released the 2.2.5 version w/ some more bugfixes. If you're still having issues just open another ticket and we'll get it sorted out.
