### ISSUE TITLE
Import scan from HP WebInspect 10.40.244.10 fails

### ISSUE THREAD

**Issue by hoggmania** [denimgroup/threadfix#1162]
When i try to manually scan from HP WebInspect 10.40.244.10 it fails stating that "Failed to determine the scan type."

Have I missed some details on how to export the report from WebInspect?

**Comment by d-maldonado** [comment]
When exporting the report from WebInspect be sure to select "Scan Details", and when choosing the level of detail in the settings select "Full". See attached screenshots.

![image](https://cloud.githubusercontent.com/assets/6145712/7840104/63e8b062-045b-11e5-9741-4cb6b8a3fbf6.png)

![image](https://cloud.githubusercontent.com/assets/6145712/7840112/6b72be04-045b-11e5-98e4-a8382d2550bc.png)

**Comment by hoggmania** [comment]
Thanks yes that fixed it!
