### ISSUE TITLE
Out of the box compilation fails : dev, 2.1.4 and 2.2.4 

### ISSUE THREAD

**Issue by javabeanz** [denimgroup/threadfix#1190]
If I checkout Threadfix, I would expect it to compile right out of the box. But :
 - ZapProxy dependencies are not found
 - ESAPI dependency is not found
 - after removing these issues, the compilation fails on threadfix-main 

Please resolve these issues, or help me out.

**Comment by d-maldonado** [comment]
Did you have a chance to checkout our WIKI page [Development Environment Setup](https://github.com/denimgroup/threadfix/wiki/Development-Environment-Setup#running-threadfix-without-an-ide), in particular the section **Running ThreadFix Without an IDE**.

If you wish to just build ThreadFix you should be able to use the Maven command:  ```mvn clean install```

**Comment by javabeanz** [comment]
I just wish to build Threadfix, and it fails. I am using Maven 3.2.1 and jdk 7. The ZapProxy ans ESAPI snapshot dependencies are not in the Maven central repo, so that will fail anyway.

**Comment by dg-mcollins** [comment]
Hi, sorry to hear ThreadFix is giving you so much trouble.

We include those artifacts locally in the source tree. So while you are correct that those two dependencies are not in Maven Central, our CI and developers build successfully and regularly. If you could include the commands you use to compile ThreadFix, the branch you're trying to compile, and the corresponding error messages I'm sure we can figure out what's happening here.

Thanks,
Mac

**Comment by javabeanz** [comment]
compile command : mvn clean install 
branch : 2.2.7
errors :


[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.
3.2:compile (default-compile) on project threadfix: Compilation failure: Compila
tion failure:
[ERROR] \dev\ws\threadfix2\threadfix-main\src\main\java\com\denimgroup\threadfix
\service\repository\GitServiceImpl.java:[175,67] error: no suitable method found
 for decrypt(String)
[ERROR] \dev\ws\threadfix2\threadfix-main\src\main\java\com\denimgroup\threadfix
\service\repository\GitServiceImpl.java:[176,67] error: no suitable method found
 for decrypt(String)
[ERROR] \dev\ws\threadfix2\threadfix-main\src\main\java\com\denimgroup\threadfix
\service\RemoteProviderTypeServiceImpl.java:[238,45] error: no suitable method f
ound for encrypt(String)
[ERROR] \dev\ws\threadfix2\threadfix-main\src\main\java\com\denimgroup\threadfix
\service\RemoteProviderTypeServiceImpl.java:[241,47] error: no suitable method f
ound for encrypt(String)
[ERROR] \dev\ws\threadfix2\threadfix-main\src\main\java\com\denimgroup\threadfix
\service\RemoteProviderTypeServiceImpl.java:[242,47] error: no suitable method f
ound for encrypt(String)
[ERROR] \dev\ws\threadfix2\threadfix-main\src\main\java\com\denimgroup\threadfix
\service\RemoteProviderTypeServiceImpl.java:[247,47] error: no suitable method f
ound for encrypt(String)
[ERROR] \dev\ws\threadfix2\threadfix-main\src\main\java\com\denimgroup\threadfix
\service\RemoteProviderTypeServiceImpl.java:[269,36] error: no suitable method f
ound for decrypt(String)
[ERROR] \dev\ws\threadfix2\threadfix-main\src\main\java\com\denimgroup\threadfix
\service\RemoteProviderTypeServiceImpl.java:[272,38] error: no suitable method f
ound for decrypt(String)
[ERROR] \dev\ws\threadfix2\threadfix-main\src\main\java\com\denimgroup\threadfix
\service\RemoteProviderTypeServiceImpl.java:[273,38] error: no suitable method f
ound for decrypt(String)
[ERROR] \dev\ws\threadfix2\threadfix-main\src\main\java\com\denimgroup\threadfix
\service\RemoteProviderTypeServiceImpl.java:[279,37] error: no suitable method f
ound for decrypt(String)
[ERROR] \dev\ws\threadfix2\threadfix-main\src\main\java\com\denimgroup\threadfix
\service\ApplicationServiceImpl.java:[714,54] error: no suitable method found fo
r encrypt(String)
[ERROR] \dev\ws\threadfix2\threadfix-main\src\main\java\com\denimgroup\threadfix
\service\ApplicationServiceImpl.java:[715,54] error: no suitable method found fo
r encrypt(String)....

Maybe travis automated build service could be used.

**Comment by javabeanz** [comment]
Adding the jars that are checked into the git repo with these statements :

mvn install:install-file -Dfile=esapi-2.1.0-SNAPSHOT.jar -DgroupId=org.owasp.esapi -DartifactId=esapi -Dversion=2.1.0-SNAPSHOT -Dpackaging=jar
mvn install:install-file -Dfile=zap-2.2.2.jar -DgroupId=com.owasp.zap -DartifactId=zap -Dversion=2.2.2 -Dpackaging=jar
mvn install:install-file -Dfile=zaphelp-2.2.2.jar -DgroupId=com.owasp.zap -DartifactId=zaphelp -Dversion=2.2.2 -Dpackaging=jar
mvn install:install-file -Dfile=xom-1.2.6.jar -DgroupId=com.owasp.zap -DartifactId=xom -Dversion=1.2.6 -Dpackaging=jar
mvn install:install-file -Dfile=java-getopt-1.0.13.jar -DgroupId=com.owasp.zap -DartifactId=java-getopt -Dversion=1.0.13 -Dpackaging=jar
mvn install:install-file -Dfile=jgoodies-looks-2.4.0.jar -DgroupId=com.owasp.zap -DartifactId=jgoodies-looks -Dversion=2.4.0 -Dpackaging=jar
mvn install:install-file -Dfile=lablib-checkboxtree-3.2.jar -DgroupId=com.owasp.zap -DartifactId=lablib-checkboxtree -Dversion=3.2 -Dpackaging=jar
mvn install:install-file -Dfile=com.microsoft.tfs.sdk-11.0.0.jar -DgroupId=com.microsoft.tfs.sdk -DartifactId=com.microsoft.tfs.sdk  -Dversion=11.0.0 -Dpackaging=jar

This fixes my build, but it's quite cumbersome.
