### ISSUE TITLE
Improve WebInspect Importer (previously GC#94)

### ISSUE THREAD

**Issue by dorindareyna** [denimgroup/threadfix#12]
Reported by mcoll...@denimgroup.com, Jul 9, 2012 
Our WebInspect importer needs more testing with more scan files to make sure that it works. We also need to make sure there are no format changes with the current version and that our vuln DB entries are up to date.

**Comment by dancornell** [comment]
The WebInspect importer has been through a number of updates since this was filed. If folks run into any remaining unmapped findings please submit a new defect request for the specific type(s) and we'll get those fixed.
