### ISSUE TITLE
Improve error messages in Burp plugin

### ISSUE THREAD

**Issue by dg-mcollins** [denimgroup/threadfix#1219]
The Burp plugin currently allows users to submit scans with no vulnerabilities to ThreadFix, resulting in a confusing error message. Let's check to make sure that there are actual vulnerabilities before we roll up the scan and export it.

**Comment by dancornell** [comment]
Presumably that is something we can detect inside the plugin (what version of Burp is running)?

**Comment by dg-mcollins** [comment]
Yeah we should probably do a sanity check when the plugin starts up and display a message to the user if it fails
