### ISSUE TITLE
Bash install script errors

### ISSUE THREAD

**Issue by travisaltman** [denimgroup/threadfix#135]
mint zip # ./threadfix.sh 
chmod: cannot access ‘././tomcat/bin/*.sh’: No such file or directory
readlink: missing operand
Try 'readlink --help' for more information.
dirname: missing operand
Try 'dirname --help' for more information.
$Looking for a key in /home/travis/threadfix/threadfix-main/util/zip/tomcat/keystore
./threadfix.sh: 25: ./threadfix.sh: /..//bin/keytool: not found
Keystore Generation failed.

**Comment by dancornell** [comment]
Closing this out as we haven't heard any feedback for some time.
We've also moved away from Google Code downloads. Packaged downloads can now be found here:
http://www.threadfix.org/download/
