### ISSUE TITLE
Reports page: Dropdown not long enough for contents

### ISSUE THREAD

**Issue by marmotworks** [denimgroup/threadfix#151]
1. Navigate to the reports page.
2. Select '12 Month Vulnerability Breakdown' in the dropdown, if it is not already selected.

Expected Result: Dropdown is long enough to contain text.
Actual Result: Dropdown clips text.

**Comment by dancornell** [comment]
Reporting UI has been updated in the 2.2 development effort so that this is no longer an issue. Can get 2.2 downloads from here:
http://www.denimgroup.com/blog/denim_group/2015/01/threadfix-2m6-now-available.html
