### ISSUE TITLE
Reports page: graph header font is inconsistant

### ISSUE THREAD

**Issue by marmotworks** [denimgroup/threadfix#152]
1. Navigate to the Reports page.
2. Select each type of report from the dropdown on the trending, snapshot, and comparison tabs. Observe the fonts used.

Expected result: Fonts are consistent with the rest of the application.
Actual result: Fonts vary between various reports and application.

**Comment by dancornell** [comment]
Fixed in 2.2 development. Downloads available here:
http://www.denimgroup.com/blog/denim_group/2015/01/threadfix-2m6-now-available.html
