### ISSUE TITLE
ThreadFix uses a component with a known critical security vulnerability

### ISSUE THREAD

**Issue by ElColmo** [denimgroup/threadfix#1594]
ThreadFix is known to use a version of commons-collections.jar that has a known critical security vulnerability.

The file location  "ThreadFix_2.2.7.2/tomcat/webapps/threadfix/WEB-INF/lib/commons-collections-3.2.1.jar" contains an instance of version 3.2.1 of the Commons Collections Java artefact.

I recommend upgrading this Commons Collections component to the latest stable version.  Versions from 3.2.2 onwards are known to fix the remote command execution vulnerability in question.

References: 
https://commons.apache.org/proper/commons-collections/release_3_2_2.html
https://issues.apache.org/jira/browse/COLLECTIONS-580
http://foxglovesecurity.com/2015/11/06/what-do-weblogic-websphere-jboss-jenkins-opennms-and-your-application-have-in-common-this-vulnerability/

**Comment by ElColmo** [comment]
Hi Denim Group. Could we possibly have a comment on the status of this issue?  

Thanks!
ElColmo

**Comment by dg-mcollins** [comment]
Hello,

First off, thanks for pointing this out. I forgot to close the issue, but I committed a fix in dev a little after you posted the issue:

https://github.com/denimgroup/threadfix/commit/b3d004a662fc3f14744a1a53861dcd19e5bbb7e0

All future ThreadFix releases will have the patched library.

Thanks,
Mac
