### ISSUE TITLE
Add Black Duck Support

### ISSUE THREAD

**Issue by holograham** [denimgroup/threadfix#1758]
Adding Black Duck Support for Vulnerability de-duplication

**Comment by kylepippin** [comment]
Thank you for your suggestion!  We have received numerous requests for this integration, so I'm pleased to announce that ThreadFix Enterprise will have Black Duck support in our upcoming version 2.4.  Currently scheduled for release in June 2016.  

For more information regarding this integration, or any other non-technical inquiries, please visit us on our new website: [http://www.threadfix.it/contact/](http://www.threadfix.it/contact/)
