### ISSUE TITLE
JIRA Integration - Will not allow project names >50 Characters

### ISSUE THREAD

**Issue by thurmond** [denimgroup/threadfix#1760]
Configuring a new Defect Tracker that links to a project with a name >50 characters from the Settings Menu enforces a restriction that JIRA Project Names cannot be longer than 50 characters and will not permit creation of the link.

Linking an from within an existing application to the same JIRA project name functions without issue.

By Default, JIRA permits 80 character names; and this is configurable by the JIRA admin.

See - https://confluence.atlassian.com/jira064/configuring-jira-options-720411998.html

**Comment by d-maldonado** [comment]
Thurmond,

Thank you for brining this to our attention. An enhancement has been filed. 

Daniel Maldonado
