### ISSUE TITLE
threadfix.sh bash

### ISSUE THREAD

**Issue by h00dini** [denimgroup/threadfix#1762]
I am trying to set up the free trial and am not able to get threadfix running. I have Tomcat up and all the software required, but can't find the threadfix.sh to run. I ran wget on the URL provided to get the zip. Shouldn't I of gotten a WAR to unpackage? Thanks.

**Comment by d-maldonado** [comment]
h00dini,

We have changed how we distribute the trial version of ThreadFix. In the past we sent everything (Tomcat/Java/ThreadFix) in a self contained zip and used a start-up (threadfix.sh) script to kick everything off.

We now distribute a zip of the exploded WAR. After unzipping you should be left with a 'threadfix' folder that can be dropped in the **webapps** directory of Tomcat(installed as a service). 

Daniel M

**Comment by bethbuhawe** [comment]
Hi,

I've downloaded the zip file and dropped the threadfix folder in the webapps directory of tomcat. However, I can't seem to get threadfix up and running. Tomcat on the other hand seems to be running and can be accessed via browser. Btw, I've downloaded ThreadFix-2.4.1 Trial version and the said folder contains the following : fortify-plugin.jar, threadfix (folder) and ThreadFix 2.4.1 ReadMe.txt

Any thoughts why it's still not running when I access it via http://IP:8080/threadfix ?

**Comment by joaquinrinaudo-olx** [comment]
I'm running into the same problem.

**Comment by hruiz-dg** [comment]
Greetings and thank you for your interest in ThreadFix.

To ensure you're evaluating the latest Enterprise version, please visit the following page and download the trial: https://threadfix.it

...and follow the installation instructions at: https://denimgroup.atlassian.net/wiki/display/TDOC/Installation+and+Upgrade+Guide

If you have any questions or to report an issue, please email our support at: support@threadfix.it

Thanks again, and we look forward to the opportunity to earn your business.
