### ISSUE TITLE
Archer export creates error

### ISSUE THREAD

**Issue by robertbaumann** [denimgroup/threadfix#1764]
Archer Export
Generate Archer Output
Status: Issue with locating/generating file.

**Comment by d-maldonado** [comment]
Robert,

Have you configured your file upload location? 
System Settings -> Other Settings -> File Upload Location

If you have, I would double check and ensure that the user running Tomcat has permission for the defined directory.

That being said, if your permissions are correct and the file upload location is a valid directory check if any errors are produced in [threadfix.log](https://github.com/denimgroup/threadfix/wiki/Debugging-ThreadFix-Issues#log-messages). 

Daniel Maldonado

**Comment by robertbaumann** [comment]
Thank you for the tip. After setting the File Upload Location the archer export generates properly. The association between archer export and file upload location wasn't clear.
