### ISSUE TITLE
Is the project still current

### ISSUE THREAD

**Issue by nhajiyani** [denimgroup/threadfix#1777]
Hi,
I see the last commit was back in mid 2016, is this project still being supported and will receive bug fixed or new features in the future?

Thanks.

**Comment by dancornell** [comment]
The vast majority of the development for the past year and a half has gone into the Enterprise Edition:
https://www.threadfix.it/download/trial/

That said, we are currently working on a government-funded contract that will provide some updates to this codebase. That will provide bugfixes and modernization of the codebase and the results will be released open source. The only challenge is that we're not in control of the release of the code developed via that contract. We're hoping it will be available soon and will provide more information as soon as we can.

**Comment by drequil** [comment]
Thanks Dan.
