### ISSUE TITLE
Pre-installed VM appliance to use for Virtualbox

### ISSUE THREAD

**Issue by nhajiyani** [denimgroup/threadfix#1778]
As mentioned in this link here
https://www.denimgroup.com/blog/2012/08/threadfix-fortify-imperva-vm-appliance-oh-my/

about a Pre-installed VM appliance 
http://code.google.com/p/threadfix/wiki/ThreadFixVMAppliance

This link has expired - Is there a way this has been hosted somewhere else?

**Comment by dancornell** [comment]
We didn't see a lot of usage of the pre-install VM image so it hasn't been maintained. We do have an AWS image of TheadFix Enterprise that we can share will folks. If you can provide us with an AWS account number and the AWS region where you want to use it, we can share it with you. This could be submitted via the ThreadFix contact form:
https://www.threadfix.it/contact/

Please mention that you would like access to the pre-installed AWS image.
