### ISSUE TITLE
"Check Remote Provider Application Import Status" returns status for all remote apps

### ISSUE THREAD

**Issue by danrussell9386** [denimgroup/threadfix#1781]
The REST call documented [here](https://denimgroup.atlassian.net/wiki/display/TDOC/Check+Remote+Provider+Application+Import+Status) states that calling the following URL 

{code}
`/rest/remoteprovider/remoteProviderApplication/{remoteProviderApplicationId}/status` 
{code}

will return the  import status for the remote provider application associated with the ID.  In practice though it appears to return the import status for ALL remote providers associated with the same application.

**Comment by amontzDG** [comment]
Hi,

We'd like to respond directly to you. Can you send your email address to amontz@denimgroup.com?

Thanks,
Andrew
