### ISSUE TITLE
Reports Page: Comparison by Vulnerability Type off centered

### ISSUE THREAD

**Issue by d-maldonado** [denimgroup/threadfix#189]
1. Navigate to Reports Page, select the Comparison tab.
  * *Note: this might require scans from many different sources*

![image](https://f.cloud.github.com/assets/6145712/2141430/dfef28c8-9358-11e3-9be3-d3d9047bc5f1.png)

**Comment by dancornell** [comment]
Fixed in 2.2 development. Downloads available here:
http://www.denimgroup.com/blog/denim_group/2015/01/threadfix-2m6-now-available.html
