### ISSUE TITLE
Implement (new) project root visualization (previously GC#149)

### ISSUE THREAD

**Issue by dorindareyna** [denimgroup/threadfix#19]
Reported by sspring...@axway.com, Sep 10, 2012 
When editing an application after a scan has been uploaded, the 'Project Root' displays. In my case, it appears the directories, packages, and class names are derived from the Fortify FPR import.

The visualization is not meaningful and is very confusing. This should be changed to a more elegant metaphor such as a combination of tree and listgrid. Currently it's presented in a table with radio buttons and no explanation on why things are in certain cells. Only after careful examination does it make sense.

Additionally, only a small portion of the directories, packages and classes are listed so if the project root doesn't exist on this page, there is no way to set it. So, the results need to be dynamic, either through pagination or via ajax whenever a tree is expanded for example.
    
![screenshot at 2012-09-10 14_03_08](https://f.cloud.github.com/assets/6164857/1735345/4714a04a-6353-11e3-9f8f-64830bb73c69.png)

**Comment by dancornell** [comment]
We've pulled this visualization for the foreseeable future. This wasn't super helpful and was kind of a mess.
