### ISSUE TITLE
Improve the scan test suite

### ISSUE THREAD

**Issue by dg-mcollins** [denimgroup/threadfix#208]
Our scan test suite is functional, but needs updating. Specifically, we need complete scans for each scanner that we have access to. Complete means that every type the scanner has is represented in the scan file. Once a complete scan has been added to the suite and the test cases pass, we can be confident in our importer.

**Comment by dancornell** [comment]
We now have (DG-internal) scan unit tests. These can always get better, but we've come a long way. Closing this out.
