### ISSUE TITLE
Specify IssueType or at least Default Issue Type when submitting defects

### ISSUE THREAD

**Issue by nidkhoury** [denimgroup/threadfix#209]
This is an enhancement and not a bug.
Summary: It'll be great if I can specify the issue type of the defect I'm submitting. 

Details: Currently, all issues are added to JIRA as Bugs. We currently use an Issue Type "Security Vulnerability" in JIRA so we developers can identify Security Bugs from non security related software  bugs. I can't seem to specify this type (I have the IssueTypeId too) from ThreadFix. It would be great if I can associate a Default Issue Type per application or as a Global Variable ( which is set to "Bug" by default).

**Comment by dancornell** [comment]
Updated in the 2.2 development branch. Now you can choose the JIRA template to use to create the issue (doesn't just force you to create Bugs)
Can get 2.2 builds here:
http://www.denimgroup.com/blog/denim_group/2015/01/threadfix-2m6-now-available.html
