### ISSUE TITLE
Qualys import

### ISSUE THREAD

**Issue by aaronweaver** [denimgroup/threadfix#215]
Are there any special permissions I need to give the Qualys user for importing results? I'm using Qualys (EU) and do have a WAS application setup. (V2 final)

INFO [http-bio-8443-exec-5] QualysRemoteProvider.fetchApplications(193) | Fetching Qualys applications.
WARN [http-bio-8443-exec-5] QualysRemoteProvider.fetchApplications(216) | No Qualys applications were found. Check your configuration.

**Comment by dancornell** [comment]
This should now be working in the 2.2 branch. Qualys imports have been significantly enhanced. Builds available here:
http://www.denimgroup.com/blog/denim_group/2015/01/threadfix-2m6-now-available.html
