### ISSUE TITLE
Feature Request - Add Rally Defect Tracker Support

### ISSUE THREAD

**Issue by aparsons** [denimgroup/threadfix#219]
Will you add Rally (http://www.rallydev.com) as a Defect Tracker?

You may be able to leverage their API Toolkit: https://github.com/RallyTools/RallyRestToolkitForJava
https://github.com/RallyTools/RallyRestToolkitForJava/releases

Key elements to accomplish:
* Rally integration in a defect tracker plugin
* Support the same level of functionality as JIRA (including automatic defect creation)
* Document the endpoints (of SDK functions) that are relevant in our wiki

**Comment by vstarostenko** [comment]
Hi Dan,
Upgraded to 2.2 yesterday, really liking it. 
We also want to request Rally support. Most of our business teams use Rally to raise and track defects.

Thank you.

**Comment by dancornell** [comment]
Glad you're liking 2.2. Your interest in Rally has been noted!

**Comment by renehdz** [comment]
Rally integration is available in ThreadFix 2.5.1
