### ISSUE TITLE
Ability to run reports for a designated period of time (previously GC#171)

### ISSUE THREAD

**Issue by dorindareyna** [denimgroup/threadfix#22]
Reported by brian.ma...@gmail.com, Nov 9, 2012 
Provide the option to allow users to select a date range for running reports

**Comment by dancornell** [comment]
This is now available in the 2.2 development series where we've completely revamped the reporting, adding the ability to filter by dates as well as other fields. Available for testing with the current dev release and beyond:
http://www.denimgroup.com/blog/denim_group/2015/01/threadfix-2m6-now-available.html
