### ISSUE TITLE
Number of Vulnerabilities not updating

### ISSUE THREAD

**Issue by nidkhoury** [denimgroup/threadfix#267]
I'm not sure if this is by Design but it's worth checking:
Under Dashboard > Recent Uploads. Under each application it shows the number of Vulnerabilities. I closed a few vulnerabilities and marked a few more as False Positives, but the number of Vulnerabilities on the Dashboard remains unchanged.
Again, maybe this is done by Design but I wanted to check.

Cheers!

**Comment by dancornell** [comment]
This functionality is currently behaving as-designed.
