### ISSUE TITLE
Support for DotDefender WAF (previously GC#235)

### ISSUE THREAD

**Issue by dorindareyna** [denimgroup/threadfix#35]
Reported by dancorn...@gmail.com, Feb 22, 2013 
Add support for the DotDefender WAF:
http://www.applicure.com/Products/dotdefender

[this is based on a request from a presentation at the OWASP Phoenix chapter]

**Comment by dancornell** [comment]
Haven't had any further requests for DotDefender support since an OWASP Phoenix talk a couple of years ago. Closing out for now until we determine that there is more community interest.
