### ISSUE TITLE
Add Fortify SSC support as a Remote Provider

### ISSUE THREAD

**Issue by macacollins** [denimgroup/threadfix#424]
We should be able to connect to Fortify SSC and pull scans. This would make integration much easier for large organizations that use SSC.

I anticipate that we can use our existing parsers, but we might need to update our data models to record scanning tool and channel type.

Dan Hall is trying to get us an internal instance to connect to, but in the meantime let's start looking at their API.

This should be developed as a plugin.

SscDocumentation.zip (file://SATMOBILE117/Users/rhernandez/Drop/SscDocumentation.zip)

**Comment by Ruben-E** [comment]
It's been a while. Although, any updates on this?

**Comment by kylepippin** [comment]
Your timing is incredible, Ruben!  ThreadFix Enterprise 2.5 is about to head out the door first thing next week.  About 1 to 2 weeks after that, we'll be providing the SSC RemoteProvider plugin to our customers!  

Check out our website for other exciting updates at https://www.threadfix.it
