### ISSUE TITLE
Issue uploading older scan file types (previously GC#269)

### ISSUE THREAD

**Issue by dorindareyna** [denimgroup/threadfix#46]
Reported by brian.ma...@gmail.com, May 23, 2013 
If I upload a scan file from May 2013 into ThreadFix, then I try to upload a scan file (of the same application) from April 2013 I receive an error message of "A newer scan from this scanner has been uploaded." 

This means if I do not upload historical scan data (in order of oldest scan to newest scan), the system will not let me upload the scan at all.

Seems like a user should be able to upload a scan file (unless it's a duplicate of an existing file) regardless of the order in which they upload files.

**Comment by dancornell** [comment]
There are a number of complications that implementing this would add to the merge engine. Currently this limitation is "as-designed" so we are not going to implement this at the current time.
