### ISSUE TITLE
Add Getting Started Wizard to ThreadFix (previously GC#270)

### ISSUE THREAD

**Issue by dorindareyna** [denimgroup/threadfix#47]
Reported by brian.ma...@gmail.com, May 23, 2013 
This feature would walk new users through system setup: (adding users/roles, adding teams/apps, configuring DT and WAFs, etc)

**Comment by dancornell** [comment]
We already do a bit of this in-app and have a Getting Started Guide:
https://github.com/denimgroup/threadfix/wiki/Getting-Started
That should be sufficient at the current time.
