### ISSUE TITLE
Add scan type toggle for scanners (ie. vendors like veracode) that offer both static and dynamic scans (previously GC#275)

### ISSUE THREAD

**Issue by dorindareyna** [denimgroup/threadfix#51]
Reported by brian.ma...@gmail.com, May 23, 2013 
Allow the user to chose the type of scan that is uploaded from veracode, or autodetect the scan type

**Comment by dancornell** [comment]
We currently auto-detect the vulnerability type so that we can create the proper Finding types. This is essentially fixed.
