### ISSUE TITLE
Add Big Red Button concept (previously GC#277)

### ISSUE THREAD

**Issue by dorindareyna** [denimgroup/threadfix#53]
Reported by brian.ma...@gmail.com, May 23, 2013 
Add the big red buttons concept to allow users immediate access to the top 3-4 actions on the associated page. These BRB can sit at the top of the page, or where it makes the most sense

**Comment by dancornell** [comment]
We already do a bit of this in-app and have a Getting Started Guide:
https://github.com/denimgroup/threadfix/wiki/Getting-Started
That should be sufficient at the current time.
