### ISSUE TITLE
Add # of vulnerabilities remediated to the 6-month Vulnerability Burndown on the Dashboard  (previously GC#284)

### ISSUE THREAD

**Issue by dorindareyna** [denimgroup/threadfix#54]
Reported by brian.ma...@gmail.com, Jun 4, 2013 
In response to several comversations we've had with fortune 500 companies. It's great to pair the good (we fixed X quantity) with the not so good (we identified Y many more vulnerabilities). Argument can be made that a trend line showing fewer vulnerabilities already serves this function, however there is value in stating X number of vulns have been fixed, versus implying that there are Y fewer vulnerabilities (now) in the system. Idea being add a second bar to each month showing the total number of vulnerabilities fixed.

**Comment by dancornell** [comment]
The 2.2 development branch now has a Remediation report that outlines this information as well as a lot more detail. Closing out.
