### ISSUE TITLE
Make vulnerability "scan dates" editable (previously GC#286)

### ISSUE THREAD

**Issue by dorindareyna** [denimgroup/threadfix#55]
Reported by dancorn...@gmail.com, Jun 5, 2013 
Some users would like to have the ability to change the scan date of a vulnerability. This could be used to correct situations where importers bring in vulns with incorrect scan dates such as:
https://code.google.com/p/threadfix/issues/detail?id=285

Before deciding to implement this we would need to look at possible audit trail implications.

**Comment by dancornell** [comment]
We've fixed the bug that led to the bad scan date. Now for audit purposes we don't want to allow folks to move vulnerability dates around.
