### ISSUE TITLE
Support for WhiteHat Source (previously GC#437)

### ISSUE THREAD

**Issue by brianmather** [denimgroup/threadfix#6]
Reported by gnomemade, Nov 11, 2013
Are there any plans to include support for WhiteHat Sentinel Source into Threadfix?

**Comment by dancornell** [comment]
Had a request from @sec_prof to get this working. Reached out to WhiteHat to get an API key for an account with some demo data for their static analysis.

**Comment by dancornell** [comment]
We now have access to an account with WhiteHat static data, so work on this is progressing.
