### ISSUE TITLE
Allow per-user defect tracker credentials (previously GC#310)

### ISSUE THREAD

**Issue by dorindareyna** [denimgroup/threadfix#60]
Reported by mcoll...@denimgroup.com, Jul 19, 2013 
Some users want more flexibility than the current ThreadFix defect tracker integration affords. One solution would be to allow each user to store in-session defect tracker credentials.

**Comment by dancornell** [comment]
We've talked to some more users and this hasn't been an issue. Going to stick with our current level of granularity for connecting to defect trackers.
