### ISSUE TITLE
Add ability to export configuration to a file, then import it back to ThreadFix after updates (previously GC#314)

### ISSUE THREAD

**Issue by dorindareyna** [denimgroup/threadfix#63]
Reported by mcoll...@denimgroup.com, Jul 19, 2013 
Some configuration (Active Directory integration and database strings at least) should be saved in an external place to ease the update process. This could be handled through the web interface or through a Swing application.

**Comment by dancornell** [comment]
Instead of building this, we're going to focus our efforts on providing documentation and utilities for upgrading ThreadFix servers to new versions. If folks need to copy a configuration they can just copy the database and point a new web server at the copied database.
