### ISSUE TITLE
Create wiki page with Debian setup instructions

### ISSUE THREAD

**Issue by dancornell** [denimgroup/threadfix#639]
Use the following text as a basis for a wiki page writeup on setting up ThreadFix for Debian users
---------
Install Debian's Tomcat7 and MySQL (no idea why the default pack doesn't work on Debian but it doesn't at all)
Put the war file found in the Threadfix/tomcat/webapps fir in the zip to /var/lib/tomcat7/webapps dir (that seems to auto deploy it, otherwise go to the manager page and deploy the app pointing to the war file on your system where ever it is and giving it the context of /threadfix, I think the /threadfix is hard coded in some places picking a different name didn't work out so well for me to stick to that one)
Follow the MySQL directions https://code.google.com/p/threadfix/wiki/UsingMySQL (which are not step by step and requires some MySQL googling if you don't know it)
Edit the /etc/defaults/tomcat7 file and replace JAVA_OPTS="-Djava.awt.headless=true -Xmx128m -XX:+UseConcMarkSweepGC" with JAVA_OPTS="-Djava.awt.headless=true -Xms512m -Xmx1024m -XX:+UseConcMarkSweepGC"
Restart tomcat /etc/init.d/tomcat7 start

**Comment by dg-mcollins** [comment]
https://groups.google.com/forum/#!msg/threadfix/fogof0kb6_Q/bUQ2w5033VMJ
