### ISSUE TITLE
Add more information about vulnerability types to ThreadFix (previously GC#326)

### ISSUE THREAD

**Issue by dorindareyna** [denimgroup/threadfix#68]
Reported by mcoll...@denimgroup.com, Jul 29, 2013 
It could be helpful for developers to have access to more information about what vulnerabilities are and how to fix them inside the ThreadFix UI.

**Comment by dancornell** [comment]
This has been implemented through the 2.0, 2.1 and 2.2 development cycles. We now import request, response, and other data. Closing this broadly-worded bug out. Will re-file more specific bugs/feature requests for specific info and specific scanners if needed in the future.
