### ISSUE TITLE
Review order logic on Portfolio Scan Stats (Report) (previously GC#362)

### ISSUE THREAD

**Issue by dorindareyna** [denimgroup/threadfix#79]
Reported by brian.ma...@gmail.com, Sep 11, 2013 
See attached. Let's decided on a data ordering for this (alphabetical by team/app) or grouped by criticality

![report_snapshot_portfolio_scan stats](https://f.cloud.github.com/assets/6164857/1737642/8bad98f6-6376-11e3-9a59-012a96b40fa1.PNG)

**Comment by dancornell** [comment]
This report has been dropped during the 2.2 development branch. We will likely re-add a report with some similar capabilities in the future. We can make decisions about ordering, etc at that time.
