### ISSUE TITLE
WAF application detail page does not reflect WAF status

### ISSUE THREAD

**Issue by RTimmonsDG** [denimgroup/threadfix#909]
After assigning a WAF to an application in the Edit Application modal, the WAF field in the modal does not reflect the assigned WAF, even after a refresh.  The user can verify that the WAF is assigned to the application by navigating to the cog menu > WAFs > Rules.
![wafappissue1](https://cloud.githubusercontent.com/assets/10927116/6271087/08fb4a62-b824-11e4-9e38-0fa3aae505ed.png)

Similarly, when assigning a "None" WAF to an application to clear the WAF, an error message is displayed, but the WAF is no longer assigned to the app in the WAF Rules page.
![wafappissue2](https://cloud.githubusercontent.com/assets/10927116/6271130/52a606b6-b824-11e4-99a1-2bebfeceaca0.png)

**Comment by RTimmonsDG** [comment]
This is related to issue #907.

**Comment by dg-mcollins** [comment]
I can't reproduce this on current dev (commit ID e81a94a2d9348e0a2480c536049825904f145392)
