### ISSUE TITLE
CSV2SSVL doesn't recognize quoted filepaths

### ISSUE THREAD

**Issue by RTimmonsDG** [denimgroup/threadfix#943]
CSV2SSVL will either reprompt for the file path or display an error message when entering a file path surrounded by quotes.  Quotes encapsulate file paths with spaces and is also the default format when copying a location from the Windows context menu, so it would be convenient for CSV2SSVL to accept this format, likely by stripping the quotation marks.

**Comment by dancornell** [comment]
May want to test on Linux, OS X, and Windows. Command-line behavior (like file globbing) can happen differently in different OS environments.
