### ISSUE TITLE
Deep link a vulnerability

### ISSUE THREAD

**Issue by aaronweaver** [denimgroup/threadfix#966]
Where possible deep link a vulnerability back to the source. For example Checkmarx XML has an attribute called DeepLink that takes you right to that vulnerability within the Checkmarx web application.

**Comment by aaronweaver** [comment]
What does this mean? Feature not accepted, completed or already in another request?

**Comment by brianmather** [comment]
Aaron,

Apologies for the confusion. Actually quite the oppposite.  The request has been fulfilled, and will be available in the ThreadFix 2.2 Official release that will be published next month. ThreadFix was already capturing the deep links information for several of the application scanners we integrate with, but the data wasnt being displayed in the UI.  We've remedied this, and the data will now be visible.

If you have any questions, please let us know.
-ThreadFix Support
