### ISSUE TITLE
Unable to delete API Keys 

### ISSUE THREAD

**Issue by MikePerez** [denimgroup/threadfix#984]
After deleting the API Keys and logging off or even navigating away from the page and coming back. The deleted API keys are still present. This present a risk to organization that creates API keys to third party vendors and later is unable to disable or delete those keys.

**Comment by brianmather** [comment]
Thanks for reporting the issue Mike. Can you let us know what version of ThreadFix you are currently running / experiencing this issue with?

**Comment by MikePerez** [comment]
Thanks Brian, This is for 2.2i7.

**Comment by dg-mcollins** [comment]
Commit 6f82eb95b7c5a03e46865a4d8c9f5f27ccfca8f9 addresses this issue

**Comment by MikePerez** [comment]
Thank you Brian, is that commit for RC?

**Comment by brianmather** [comment]
Unfortunately this fix did not make it into the initial release candidate that went up yesterday 3/4/15.  Worst case scenario, the solution will be included in the 2.2 Official release later this month.
